-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.emprendimientos
(
    id serial NOT NULL,
    iso3 character varying(3) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    sector character varying(100) COLLATE pg_catalog."default",
    anio_fundacion integer,
    sitio_web character varying(255) COLLATE pg_catalog."default",
    contacto character varying(150) COLLATE pg_catalog."default",
    creado_en timestamp without time zone DEFAULT now(),
    creado_por integer NOT NULL,
    CONSTRAINT emprendimientos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.indicadores
(
    num character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    nivel character varying(50) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default",
    perfil character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    fuente text COLLATE pg_catalog."default",
    web text COLLATE pg_catalog."default",
    CONSTRAINT indicadores_pkey PRIMARY KEY (num)
);

CREATE TABLE IF NOT EXISTS public.mediciones
(
    id bigint NOT NULL DEFAULT nextval('medicion_id_seq'::regclass),
    iso3 character varying(3) COLLATE pg_catalog."default" NOT NULL,
    num character varying(255) COLLATE pg_catalog."default" NOT NULL,
    datayr integer,
    value_screen numeric,
    score numeric,
    rank integer,
    CONSTRAINT medicion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.paises
(
    iso3 character varying(3) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    ingreso character varying(2) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    region_cod character varying(10) COLLATE pg_catalog."default",
    poblacion integer,
    pppgdp numeric,
    ppppc numeric,
    CONSTRAINT paises_pkey PRIMARY KEY (iso3)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    contrasenia character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT id_usuario PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_email UNIQUE (email)
);

ALTER TABLE IF EXISTS public.emprendimientos
    ADD CONSTRAINT fk_empr_pais FOREIGN KEY (iso3)
    REFERENCES public.paises (iso3) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.emprendimientos
    ADD CONSTRAINT fk_empr_usuario FOREIGN KEY (creado_por)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.mediciones
    ADD CONSTRAINT fk_medicion_indicador FOREIGN KEY (num)
    REFERENCES public.indicadores (num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mediciones
    ADD CONSTRAINT fk_medicion_pais FOREIGN KEY (iso3)
    REFERENCES public.paises (iso3) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;